### ISSUE TITLE
Problem: Automatic copying of properties might be undesirable

### ISSUE THREAD

**Issue by jlnr** [lurado/LDOLayoutVariations#3]
Example: A view controller is happily setting `self.activityIndicator.hidden` and `self.errorLabel.hidden` to `YES` or `NO` during runtime. We now apply a layout template that targets these two views, which will reset their `.hidden` property to whatever is stored in the template. -> Error

With the current version of this library, there are two workarounds:
- Whitelisting per class: Add a category to UIActivityIndicatorView and UILabel that does not include "hidden" in `transferableTemplateAttributeKeyPaths`.
- Whitelisting per instance: Add subclasses of UIActivityIndicatorView and UILabel that override `transferableTemplateAttributeKeyPaths` and do not return "hidden".

Both approaches are cumbersome and make this library harder to use.

Ideas:
1. A `BOOL` property on LDOLayoutTemplate that controls whether properties should be copied at all.
2. An `NSString` property on LDOLayoutTemplate that contains comma-separated keypaths that should be copied (per-instance whitelisting).
3. `transferableTemplateAttributeKeyPaths` returns an empty array by default and we leave it up to users to solve this problem.

**Comment by sebastianludwig** [comment]
The more I use this library the more I'm convinced including anything in `transferableTemplateAttributeKeyPaths` per default is not a good idea. If a user decides to transfer `alpha` and `hidden` on all his views, it's trivial to implement. At the moment there's no solution if a user wants to transfer some custom attributes on a custom view but not the default properties on _all_ views.

Suggestion: Check `[source respondsToSelector:]` in `[LDOLayoutTemplate-applyAttributesFrom:to:]` and only apply attributes if it returns true. The three `apply` variants may stay anyway.

That'd leave us with these tasks:
- [x] Check `respondsToSelector`
- [x] Remove `transferableTemplateAttributeKeyPaths` from `UIView` category
- [x] Update README

Opinions @jlnr ?

**Comment by jlnr** [comment]
Hmm. So `transferableTemplateAttributeKeyPaths` is still a thing, but by default it is not implemented? Why not have a category on UIView that returns an empty array?

**Comment by sebastianludwig** [comment]
Because a user couldn't implement another category on UIView also implementing `transferableTemplateAttributeKeyPaths` to "overwrite" the empty implementation. Well, he could, but the runtime behavior would be undefined.
